# Generated by Django 6.0.1 on 2026-01-31 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hall_type', models.CharField(choices=[('REGULAR', 'Regular'), ('PREMIUM', 'Premium'), ('IMAX', 'IMAX'), ('4DX', '4DX')], default='REGULAR', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=10)),
                ('seats_per_row', models.PositiveIntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['venue', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.CharField(choices=[('U', 'U - Universal'), ('UA', 'UA - Parental Guidance'), ('A', 'A - Adults Only')], default='UA', max_length=5)),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('release_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-release_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=5)),
                ('number', models.PositiveIntegerField()),
                ('seat_type', models.CharField(choices=[('REGULAR', 'Regular'), ('PREMIUM', 'Premium'), ('RECLINER', 'Recliner'), ('WHEELCHAIR', 'Wheelchair Accessible')], default='REGULAR', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='booking.hall')),
            ],
            options={
                'ordering': ['row', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='booking.hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='booking.movie')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('LOCKED', 'Locked'), ('BOOKED', 'Booked'), ('CANCELLED', 'Cancelled')], default='LOCKED', max_length=20)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.seat')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.show')),
            ],
        ),
        migrations.AddField(
            model_name='hall',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='booking.venue'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['hall', 'row', 'number'], name='booking_sea_hall_id_330dd0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('hall', 'row', 'number')},
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['start_time'], name='booking_sho_start_t_d7d750_idx'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['hall', 'start_time'], name='booking_sho_hall_id_9a023d_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['show', 'seat'], name='booking_boo_show_id_f98d8a_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='booking_boo_status_e01616_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['locked_until'], name='booking_boo_locked__38c80a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('show', 'seat')},
        ),
        migrations.AlterUniqueTogether(
            name='hall',
            unique_together={('venue', 'name')},
        ),
    ]
